export const imprints = [
    {
        id: "imp-sjplit",
        name: "SJP Lit",
        slug: "sjp-lit",
        color: "#B5502E",
        blurb: "Curated literary fiction and memoir with a sharp, character-driven voice.",
    },
    {
        id: "imp-slowburn",
        name: "Slowburn",
        slug: "slowburn",
        color: "#1E5C55",
        blurb: "Atmospheric, slow-building horror and suspense.",
    },
    {
        id: "imp-tinhouse",
        name: "Tin House",
        slug: "tin-house",
        color: "#6B4226",
        blurb: "Independent literary fiction, essays, and craft-forward storytelling.",
    },
    {
        id: "imp-crookedmedia",
        name: "Crooked Media Reads",
        slug: "crooked-media-reads",
        color: "#8C7A5B",
        blurb: "Politically engaged nonfiction and cultural commentary.",
    },
    {
        id: "imp-eviltwin",
        name: "Evil Twin",
        slug: "evil-twin",
        color: "#7A1F2B",
        blurb: "Pulpy, high-concept horror and crime fiction.",
    },
    {
        id: "imp-gillianflynnbooks",
        name: "Gillian Flynn Books",
        slug: "gillian-flynn-books",
        color: "#2E4A9E",
        blurb: "Dark, twisty thrillers and psychological suspense.",
    },
    {
        id: "imp-sweetjuly",
        name: "Sweet July Books",
        slug: "sweet-july-books",
        color: "#12384B",
        blurb: "Warm, character-forward fiction and lifestyle nonfiction.",
    },
    {
        id: "imp-atlanticeditions",
        name: "Atlantic Editions",
        slug: "atlantic-editions",
        color: "#8C6A1F",
        blurb: "Essays and journalism-driven nonfiction on culture and society.",
    },
];
export const genres = [
    { id: "g-african-american-black", name: "African American & Black", slug: "african-american-black" },
    { id: "g-american", name: "American", slug: "american" },
    { id: "g-arts-entertainment", name: "Arts & Entertainment", slug: "arts-entertainment" },
    { id: "g-biography-autobiography", name: "Biography & Autobiography", slug: "biography-autobiography" },
    { id: "g-biography-memoir", name: "Biography & Memoir", slug: "biography-memoir" },
    { id: "g-biography-autobiography-memoir", name: "Biography, Autobiography & Memoir", slug: "biography-autobiography-memoir" },
    { id: "g-classics", name: "Classics", slug: "classics" },
    { id: "g-coming-of-age", name: "Coming Of Age", slug: "coming-of-age" },
    { id: "g-contemporary", name: "Contemporary", slug: "contemporary" },
    { id: "g-essays", name: "Essays", slug: "essays" },
    { id: "g-family-life", name: "Family Life", slug: "family-life" },
    { id: "g-fantasy", name: "Fantasy", slug: "fantasy" },
    { id: "g-fiction", name: "Fiction", slug: "fiction" },
    { id: "g-historical", name: "Historical", slug: "historical" },
    { id: "g-lgbtq", name: "LGBTQ+", slug: "lgbtq" },
    { id: "g-literary", name: "Literary", slug: "literary" },
    { id: "g-literary-collections", name: "Literary Collections", slug: "literary-collections" },
    { id: "g-memoirs", name: "Memoirs", slug: "memoirs" },
    { id: "g-mystery-thriller", name: "Mystery & Thriller", slug: "mystery-thriller" },
    { id: "g-nonfiction", name: "Nonfiction", slug: "nonfiction" },
    { id: "g-poetry", name: "Poetry", slug: "poetry" },
    { id: "g-psychological", name: "Psychological", slug: "psychological" },
    { id: "g-romance", name: "Romance", slug: "romance" },
    { id: "g-scifi-fantasy", name: "Sci-Fi & Fantasy", slug: "scifi-fantasy" },
    { id: "g-science-fiction", name: "Science Fiction", slug: "science-fiction" },
    { id: "g-short-stories", name: "Short Stories", slug: "short-stories" },
    { id: "g-subjects-themes", name: "Subjects & Themes", slug: "subjects-themes" },
    { id: "g-suspense", name: "Suspense", slug: "suspense" },
    { id: "g-suspense-thriller", name: "Suspense & Thriller", slug: "suspense-thriller" },
    { id: "g-thrillers", name: "Thrillers", slug: "thrillers" },
    { id: "g-women", name: "Women", slug: "women" },
    { id: "g-womens-fiction", name: "Women's Fiction", slug: "womens-fiction" },
];
export const collections = [
    {
        id: "c-cozyhorror",
        name: "Cozy Horror",
        slug: "cozy-horror",
        description: "Dread with a blanket and a cup of tea nearby.",
        curatedBookIds: [
            "b-patricia-wants-to-cuddle",
            "b-smothermoss",
            "b-the-dark-we-know",
            "b-doomsday-heart-stealer-mask",
            "b-doomsday-wandering-hour",
            "b-these-vengeful-wishes",
        ],
    },
    {
        id: "c-rabbithole",
        name: "Down the Rabbit Hole",
        slug: "down-the-rabbit-hole",
        description: "Sharp, essayistic nonfiction that pulls a single thread until the whole sweater unravels.",
        curatedBookIds: [
            "b-carrie-carolyn-coco",
            "b-on-divas",
            "b-on-grief",
            "b-on-heroism",
            "b-on-work",
            "b-on-the-housing-crisis",
        ],
    },
    {
        id: "c-onceuponatime",
        name: "Once Upon a Time",
        slug: "once-upon-a-time",
        description: "Fairy tales and fables retold with teeth.",
        curatedBookIds: [
            "b-heir-of-illusion",
            "b-hellions",
            "b-little-foxes-took-up-matches",
            "b-queen-among-the-dead",
            "b-sour-cherry",
            "b-we-should-all-be-birds",
        ],
    },
];
export const authors = [
    { id: "a-allen", name: "Samantha Allen", slug: "samantha-allen", bio: "Journalist and novelist writing sharp, queer comic horror." },
    { id: "a-alering", name: "Alisa Alering", slug: "alisa-alering", bio: "Author of eerie, atmospheric fiction rooted in Appalachia." },
    { id: "a-lee", name: "Wen-yi Lee", slug: "wen-yi-lee", bio: "YA horror author blending Southeast Asian folklore with body horror." },
    { id: "a-clark-eliopulos", name: "Zack Loran Clark & Nick Eliopulos", slug: "clark-eliopulos", bio: "Writing duo behind the middle-grade horror series The Doomsday Archives." },
    { id: "a-montalban", name: "Vanessa Montalban", slug: "vanessa-montalban", bio: "YA author of Cuban-American gothic fantasy." },
    { id: "a-gerard", name: "Sarah Gerard", slug: "sarah-gerard", bio: "Essayist and novelist known for unflinching memoir-driven nonfiction." },
    { id: "a-kornhaber", name: "Spencer Kornhaber", slug: "spencer-kornhaber", bio: "Culture writer covering pop music and celebrity." },
    { id: "a-senior", name: "Jennifer Senior", slug: "jennifer-senior", bio: "Pulitzer Prize-winning journalist and essayist." },
    { id: "a-goldberg", name: "Jeffrey Goldberg", slug: "jeffrey-goldberg", bio: "Journalist and editor writing on politics and public life." },
    { id: "a-thompson", name: "Derek Thompson", slug: "derek-thompson", bio: "Staff writer covering economics, work, and culture." },
    { id: "a-demsas", name: "Jerusalem Demsas", slug: "jerusalem-demsas", bio: "Policy journalist focused on housing and urban life." },
    { id: "a-taylor", name: "Madeline Taylor", slug: "madeline-taylor", bio: "Fantasy author of illusion-magic epics." },
    { id: "a-elliott", name: "Julia Elliott", slug: "julia-elliott", bio: "Author of Southern gothic short fiction and novels." },
    { id: "a-kazbek", name: "Katya Kazbek", slug: "katya-kazbek", bio: "Novelist blending Slavic folklore with coming-of-age stories." },
    { id: "a-livingston", name: "Lesley Livingston", slug: "lesley-livingston", bio: "Author of YA fantasy series steeped in myth." },
    { id: "a-theodoridou", name: "Natalia Theodoridou", slug: "natalia-theodoridou", bio: "Speculative fiction writer working in myth and transformation." },
    { id: "a-buckbee-fitzgerald", name: "Brian Buckbee & Carol Ann Fitzgerald", slug: "buckbee-fitzgerald", bio: "Collaborative authors of illustrated fable-driven fiction." },
];
export const books = [
    {
        id: "b-patricia-wants-to-cuddle",
        title: "Patricia Wants to Cuddle",
        slug: "patricia-wants-to-cuddle",
        coverColor: "#B5502E",
        imprintId: "imp-sjplit",
        authorId: "a-allen",
        genreIds: ["g-fiction", "g-suspense"],
        collectionIds: ["c-cozyhorror"],
        publishDate: "2023-06-06",
        isNewRelease: false,
        isComingSoon: false,
        isBestseller: true,
        isCultClassic: false,
        synopsis: "Four reality-show contestants stranded on a remote island discover the local cryptid legend is very real, and very smitten.",
        pullQuote: "\"A gonzo, gory delight.\"",
        formats: [{ type: "hardcover", price: 26, sku: "PWC-HC", stockCount: 22 }],
        contentWarnings: ["gore"],
        isbn: "978-1-000000-10-0",
    },
    {
        id: "b-smothermoss",
        title: "Smothermoss",
        slug: "smothermoss",
        coverColor: "#1E5C55",
        imprintId: "imp-slowburn",
        authorId: "a-alering",
        genreIds: ["g-fiction", "g-suspense-thriller"],
        collectionIds: ["c-cozyhorror"],
        publishDate: "2024-03-05",
        isNewRelease: true,
        isComingSoon: false,
        isBestseller: false,
        isCultClassic: false,
        synopsis: "Two sisters hiking a haunted Appalachian trail encounter a killer, a vine-choked mystery, and the woods themselves closing in.",
        formats: [{ type: "hardcover", price: 27, sku: "SM-HC", stockCount: 19 }],
        contentWarnings: ["violence"],
        isbn: "978-1-000000-11-7",
    },
    {
        id: "b-the-dark-we-know",
        title: "The Dark We Know",
        slug: "the-dark-we-know",
        coverColor: "#12384B",
        imprintId: "imp-tinhouse",
        authorId: "a-lee",
        genreIds: ["g-fiction", "g-coming-of-age"],
        collectionIds: ["c-cozyhorror"],
        publishDate: "2024-09-24",
        isNewRelease: true,
        isComingSoon: false,
        isBestseller: false,
        isCultClassic: false,
        synopsis: "A teen returns to her hometown's night market, where the vendors sell more than food and something ancient is keeping score.",
        formats: [{ type: "hardcover", price: 24, sku: "TDWK-HC", stockCount: 16 }],
        contentWarnings: ["body horror"],
        isbn: "978-1-000000-12-4",
    },
    {
        id: "b-doomsday-heart-stealer-mask",
        title: "The Doomsday Archives: The Heart-Stealer Mask",
        slug: "doomsday-archives-heart-stealer-mask",
        coverColor: "#8C6A1F",
        imprintId: "imp-crookedmedia",
        authorId: "a-clark-eliopulos",
        genreIds: ["g-fiction", "g-mystery-thriller"],
        collectionIds: ["c-cozyhorror"],
        publishDate: "2023-08-15",
        isNewRelease: false,
        isComingSoon: false,
        isBestseller: false,
        isCultClassic: false,
        synopsis: "A middle-grade mystery about a cursed mask, a small town's secret archive, and the kids brave enough to open it.",
        formats: [{ type: "hardcover", price: 18, sku: "DA1-HC", stockCount: 30 }],
        contentWarnings: [],
        isbn: "978-1-000000-13-1",
    },
    {
        id: "b-doomsday-wandering-hour",
        title: "The Doomsday Archives: The Wandering Hour",
        slug: "doomsday-archives-wandering-hour",
        coverColor: "#6B4226",
        imprintId: "imp-eviltwin",
        authorId: "a-clark-eliopulos",
        genreIds: ["g-fiction", "g-mystery-thriller"],
        collectionIds: ["c-cozyhorror"],
        publishDate: "2024-08-13",
        isNewRelease: true,
        isComingSoon: false,
        isBestseller: false,
        isCultClassic: false,
        synopsis: "The second Doomsday Archives case: a missing hour, a town frozen in time, and a ticking clock only the kids can hear.",
        formats: [{ type: "hardcover", price: 18, sku: "DA2-HC", stockCount: 28 }],
        contentWarnings: [],
        isbn: "978-1-000000-14-8",
    },
    {
        id: "b-these-vengeful-wishes",
        title: "These Vengeful Wishes",
        slug: "these-vengeful-wishes",
        coverColor: "#7A1F2B",
        imprintId: "imp-gillianflynnbooks",
        authorId: "a-montalban",
        genreIds: ["g-fantasy", "g-coming-of-age"],
        collectionIds: ["c-cozyhorror"],
        publishDate: "2024-02-13",
        isNewRelease: false,
        isComingSoon: false,
        isBestseller: true,
        isCultClassic: false,
        synopsis: "A Cuban-American teen inherits a genie's lamp and a family curse that trades wishes for years of her life.",
        pullQuote: "\"Lush, wicked, unforgettable.\"",
        formats: [{ type: "hardcover", price: 20, sku: "TVW-HC", stockCount: 24 }],
        contentWarnings: [],
        isbn: "978-1-000000-15-5",
    },
    {
        id: "b-carrie-carolyn-coco",
        title: "Carrie Carolyn Coco",
        slug: "carrie-carolyn-coco",
        coverColor: "#A13A3A",
        imprintId: "imp-sweetjuly",
        authorId: "a-gerard",
        genreIds: ["g-biography-memoir", "g-nonfiction"],
        collectionIds: ["c-rabbithole"],
        publishDate: "2024-06-04",
        isNewRelease: true,
        isComingSoon: false,
        isBestseller: false,
        isCultClassic: false,
        synopsis: "A true-crime memoir excavating the murder of the author's friend and the fault lines it exposed in a community.",
        formats: [{ type: "ebook", price: 14, sku: "CCC-EB", stockCount: 9999 }],
        contentWarnings: ["violence", "true crime"],
        isbn: "978-1-000000-16-2",
    },
    {
        id: "b-on-divas",
        title: "On Divas",
        slug: "on-divas",
        coverColor: "#8C7A5B",
        imprintId: "imp-atlanticeditions",
        authorId: "a-kornhaber",
        genreIds: ["g-essays", "g-arts-entertainment"],
        collectionIds: ["c-rabbithole"],
        publishDate: "2024-05-07",
        isNewRelease: false,
        isComingSoon: false,
        isBestseller: false,
        isCultClassic: false,
        synopsis: "A pocket essay tracing the diva as cultural archetype, from opera houses to pop stardom.",
        formats: [{ type: "ebook", price: 9, sku: "OD-EB", stockCount: 9999 }],
        contentWarnings: [],
        isbn: "978-1-000000-17-9",
    },
    {
        id: "b-on-grief",
        title: "On Grief",
        slug: "on-grief",
        coverColor: "#6B4226",
        imprintId: "imp-sjplit",
        authorId: "a-senior",
        genreIds: ["g-essays", "g-nonfiction"],
        collectionIds: ["c-rabbithole"],
        publishDate: "2023-11-14",
        isNewRelease: false,
        isComingSoon: false,
        isBestseller: true,
        isCultClassic: false,
        synopsis: "A compact, clear-eyed essay on what mourning actually does to the mind and the body.",
        formats: [{ type: "ebook", price: 9, sku: "OGR-EB", stockCount: 9999 }],
        contentWarnings: ["grief", "loss"],
        isbn: "978-1-000000-18-6",
    },
    {
        id: "b-on-heroism",
        title: "On Heroism",
        slug: "on-heroism",
        coverColor: "#1E5C55",
        imprintId: "imp-slowburn",
        authorId: "a-goldberg",
        genreIds: ["g-essays", "g-nonfiction"],
        collectionIds: ["c-rabbithole"],
        publishDate: "2024-01-30",
        isNewRelease: false,
        isComingSoon: false,
        isBestseller: false,
        isCultClassic: false,
        synopsis: "An essay interrogating who gets called a hero, and why the label so often serves the powerful.",
        formats: [{ type: "ebook", price: 9, sku: "OH-EB", stockCount: 9999 }],
        contentWarnings: [],
        isbn: "978-1-000000-19-3",
    },
    {
        id: "b-on-work",
        title: "On Work",
        slug: "on-work",
        coverColor: "#B5502E",
        imprintId: "imp-tinhouse",
        authorId: "a-thompson",
        genreIds: ["g-essays", "g-nonfiction"],
        collectionIds: ["c-rabbithole"],
        publishDate: "2024-04-02",
        isNewRelease: true,
        isComingSoon: false,
        isBestseller: false,
        isCultClassic: false,
        synopsis: "A sharp essay on why work stopped feeling like a means to an end and became an identity.",
        formats: [{ type: "ebook", price: 9, sku: "OW-EB", stockCount: 9999 }],
        contentWarnings: [],
        isbn: "978-1-000000-20-9",
    },
    {
        id: "b-on-the-housing-crisis",
        title: "On the Housing Crisis",
        slug: "on-the-housing-crisis",
        coverColor: "#12384B",
        imprintId: "imp-crookedmedia",
        authorId: "a-demsas",
        genreIds: ["g-essays", "g-nonfiction"],
        collectionIds: ["c-rabbithole"],
        publishDate: "2024-07-16",
        isNewRelease: true,
        isComingSoon: false,
        isBestseller: false,
        isCultClassic: false,
        synopsis: "An essay diagnosing why housing got so expensive everywhere, and who benefits from keeping it that way.",
        formats: [{ type: "ebook", price: 9, sku: "OHC-EB", stockCount: 9999 }],
        contentWarnings: [],
        isbn: "978-1-000000-21-6",
    },
    {
        id: "b-heir-of-illusion",
        title: "Heir of Illusion",
        slug: "heir-of-illusion",
        coverColor: "#8C6A1F",
        imprintId: "imp-eviltwin",
        authorId: "a-taylor",
        genreIds: ["g-fantasy", "g-scifi-fantasy"],
        collectionIds: ["c-onceuponatime"],
        publishDate: "2024-10-01",
        isNewRelease: true,
        isComingSoon: false,
        isBestseller: false,
        isCultClassic: false,
        synopsis: "An illusion-mage's daughter must master a forbidden magic to keep her family's crumbling empire from being seen for what it is.",
        formats: [{ type: "hardcover", price: 27, sku: "HOI-HC", stockCount: 20 }],
        contentWarnings: [],
        isbn: "978-1-000000-22-3",
    },
    {
        id: "b-hellions",
        title: "Hellions",
        slug: "hellions",
        coverColor: "#7A1F2B",
        imprintId: "imp-gillianflynnbooks",
        authorId: "a-elliott",
        genreIds: ["g-fiction", "g-short-stories"],
        collectionIds: ["c-onceuponatime"],
        publishDate: "2023-05-16",
        isNewRelease: false,
        isComingSoon: false,
        isBestseller: false,
        isCultClassic: true,
        synopsis: "Southern gothic stories where the swamp, the church, and the woods all keep their own kind of magic.",
        formats: [{ type: "hardcover", price: 26, sku: "HEL-HC", stockCount: 14 }],
        contentWarnings: ["body horror"],
        isbn: "978-1-000000-23-0",
    },
    {
        id: "b-little-foxes-took-up-matches",
        title: "Little Foxes Took Up Matches",
        slug: "little-foxes-took-up-matches",
        coverColor: "#2E4A9E",
        imprintId: "imp-sweetjuly",
        authorId: "a-kazbek",
        genreIds: ["g-fiction", "g-coming-of-age"],
        collectionIds: ["c-onceuponatime"],
        publishDate: "2022-08-09",
        isNewRelease: false,
        isComingSoon: false,
        isBestseller: false,
        isCultClassic: true,
        synopsis: "A boy raised as a girl in Soviet Russia navigates identity and folklore in a world where household spirits still listen.",
        formats: [{ type: "hardcover", price: 27, sku: "LFTM-HC", stockCount: 12 }],
        contentWarnings: [],
        isbn: "978-1-000000-24-7",
    },
    {
        id: "b-queen-among-the-dead",
        title: "Queen Among the Dead",
        slug: "queen-among-the-dead",
        coverColor: "#1E5C55",
        imprintId: "imp-atlanticeditions",
        authorId: "a-livingston",
        genreIds: ["g-fantasy", "g-scifi-fantasy"],
        collectionIds: ["c-onceuponatime"],
        publishDate: "2024-05-14",
        isNewRelease: true,
        isComingSoon: false,
        isBestseller: false,
        isCultClassic: false,
        synopsis: "A necromancer princess must claim a throne of bones before her undead rivals claim it, and her, first.",
        formats: [{ type: "hardcover", price: 25, sku: "QATD-HC", stockCount: 17 }],
        contentWarnings: ["violence"],
        isbn: "978-1-000000-25-4",
    },
    {
        id: "b-sour-cherry",
        title: "Sour Cherry",
        slug: "sour-cherry",
        coverColor: "#B5502E",
        imprintId: "imp-sjplit",
        authorId: "a-theodoridou",
        genreIds: ["g-fantasy", "g-literary"],
        collectionIds: ["c-onceuponatime"],
        publishDate: "2024-09-03",
        isNewRelease: true,
        isComingSoon: false,
        isBestseller: false,
        isCultClassic: false,
        synopsis: "A Bluebeard retelling narrated by the son who grew inside his mother's grief, and his father's crimes.",
        pullQuote: "\"A fairy tale with teeth.\"",
        formats: [{ type: "hardcover", price: 26, sku: "SC-HC", stockCount: 15 }],
        contentWarnings: ["violence", "body horror"],
        isbn: "978-1-000000-26-1",
    },
    {
        id: "b-we-should-all-be-birds",
        title: "We Should All Be Birds",
        slug: "we-should-all-be-birds",
        coverColor: "#6B4226",
        imprintId: "imp-slowburn",
        authorId: "a-buckbee-fitzgerald",
        genreIds: ["g-fantasy", "g-family-life"],
        collectionIds: ["c-onceuponatime"],
        publishDate: "2023-10-10",
        isNewRelease: false,
        isComingSoon: false,
        isBestseller: false,
        isCultClassic: false,
        synopsis: "An illustrated fable about a village where grief turns people into birds, and the girl who refuses to fly away.",
        formats: [{ type: "hardcover", price: 24, sku: "WSABB-HC", stockCount: 10 }],
        contentWarnings: ["grief"],
        isbn: "978-1-000000-27-8",
    },
];
export function getBookBySlug(slug) {
    return books.find((b) => b.slug === slug);
}
export function getAuthorBySlug(slug) {
    return authors.find((a) => a.slug === slug);
}
export function getImprintBySlug(slug) {
    return imprints.find((i) => i.slug === slug);
}
export function getCollectionBySlug(slug) {
    return collections.find((c) => c.slug === slug);
}
export function booksByImprint(imprintId) {
    return books.filter((b) => b.imprintId === imprintId);
}
export function booksByAuthor(authorId) {
    return books.filter((b) => b.authorId === authorId);
}
export function booksByCollection(collection) {
    return collection.curatedBookIds
        .map((id) => books.find((b) => b.id === id))
        .filter((b) => Boolean(b));
}
